---
title: "Find the Best Car Value Project"
# author: "Type Your Name Here"
# date: today
format: 
    pdf:
        pdf-engine: lualatex
        template-partials:
            - ../../doc-class.tex
        documentclass: scrartcl
crossref:
    chapters: false
---


When trying to decide what car to buy, real value is not necessarily determined by how much you spend on the initial purchase. Instead, cars that are reliable and don’t cost much to own often represent the best values. But no matter how reliable or inexpensive a car may cost to own, it must also perform well.

To measure value, Consumer Reports developed a statistic referred to as a value score. The value score is based upon five-year owner costs, overall road-test scores, and predicted-reliability ratings. Five-year owner costs are based upon the expenses incurred in the first five years of ownership, including depreciation, fuel, maintenance and repairs, and so on. Using a national average of 12,000 miles per year, an average cost per mile driven is used as the measure of five-year owner costs. Road-test scores are the results of more than 50 tests and evaluations and are based on a 100-point scale, with higher scores indicating better performance, comfort, convenience, and fuel economy. The highest road-test score obtained in the tests conducted by Consumer Reports was a 99 for a Lexus LS 460L. Predicted -reliability ratings (1=Poor, 2=Fair, 3=Good, 4=Very
Good, and 5=Excellent) are based upon data from Consumer Reports’ Annual Auto Survey.

A car with a value score of 1.0 is considered to be an “average-value” car. A car with a value score of 2.0 considered to be twice as good a value as car with a value score of 1.0; a car with a value score of 0.5 is considered half as good as average; and so on. The data for three sizes of cars (13 small sedans, 20 family sedans, and 21 upscale sedans), including the price ($) of each car tested, are contained in the file named Car Values (Consumer Reports website, April 18, 2012). To incorporate the effect of size of car, a categorical variable with three values (small sedan, family sedan, and upscale sedan), use the following dummy variable:

$$
\begin{split}
\text{Family-sedan} &=\begin{cases}
1 & \text{if the car is a family sedan}\\
0 & \text{otherwise}\end{cases}\\
\text{Upscale-sedan} &=
\begin{cases}
1& \text{if the car is Upscale Seda}\\
0 &\text{otherwise}
\end{cases}
\end{split}
$$