---
title: "Quiz 3"
format: 
    pdf:
        pdf-engine: lualatex
        template-partials:
            - ../../doc-class.tex
        include-in-header:
        - text: |
            \AtBeginDocument{
                \renewcommand{\theexercise}{\arabic{exercise}}
            }
params:
    show_solution: false
filters:
    - ../../solution-filter.lua
crossref:
    chapters: false
---

# Exercises

Please use this dataset.

| x | y |
|---|---|
| 1 | 2 |
| 2 | 4 |
| 3 | 5 |
| 4 | 4 |
| 5 | 6 |
| 6 | 7 |

::: {#exr-}
Does the data provide sufficient evidence to indicate that $x$ and $y$ are significantly related? Use $\alpha = 0.05$. 

:::


::: {.answer}

```{r}
x <- c(1,2,3,4,5,6)
y <- c(2,4,5,4,6,7)
model <- lm(y~x)
summary(model)
```

Since p-value<0.05, there is sufficient evidence to indicate that $x$ and $y$ are related.

:::

::: {#exr-}
Find a 95% confidence interval for the slope, $\beta_1$. Interpret the result practically.


::: {.answer}

```{r}
confint(model, level=0.95)['x',]
```
:::



:::


